docs/Components.md, src/components/FormCard.tsx, src/utilities/FormManager.ts, src/utilities/backendValidation.ts, test/components/FormCard.test.js, test/utilities/backendValidation.test.js
`backendValidation.ts` and associated test file  was copied exactly as it exists on V2, where it has worked beautifully for a long time, and should be mostly ignored for the purposes of this code review.
Closes https://github.com/mighty-justice/fields-ant/issues/31
=> Add backend validation response processing to FormManager

src/inputs/ObjectSearchCreate.tsx, src/inputs/OptionSelect.tsx, src/inputs/OptionSelectDisplay.tsx, src/inputs/RadioGroup.tsx, src/interfaces.ts, src/utilities/common.ts, test/types/percent.test.js, test/types/radio.test.js
- Move `getOptions` into utils file
- Spend some time reducing duplication in interfaces
- Increase coverage with `radio` and `percent` test stubs
=> Move options functions into utils, other clean-ups

docs/Interfaces.md, src/building-blocks/NestedFieldSet.tsx, src/interfaces.ts, src/utilities/common.ts, test/types/objectSearchCreate.test.js
Other very small fixes:
- `IFieldSetPartial` is a super-type of `IFieldSetSimplePartial`, so this is an easy change
- `disabled` and `writeOnly` are filled in, therefore guaranteed in final `fieldConfig`
=> Clean up objectSearchCreate tests

src/interfaces.ts
optionSelect type FieldConfigs can include an `options` attribute instead, which explicitly defines the options.
=> optionType is optional in OptionSelect

src/components/FormDrawer.tsx
* Set specific `className` to help CSS customization.
* Remove hardcoded `width`, add it as a prop.
=> Improve FormDrawer customizability

src/components/FormDrawer.tsx
Ant Design default it to 256px, so I MUST set it. 🤦‍♂️ 
My fix is allowing a string so that I can set it to 100% and use max-width to control it in CSS.
It works, I tested it locally.
=> Allow FormDrawer width to be a string

src/building-blocks/CardField.tsx, src/building-blocks/CardFieldSet.tsx, src/components/ArrayCard.tsx, src/components/EditableCard.tsx, src/index.ts
- This brings `ArrayCard` in line with `Card`, `SummaryCard`, and `FormCard`.
- Also includes some small sorting improvements
=> Rename ArrayCard.extra to renderTopRight

src/components/EditableArrayCard.tsx, src/components/EditableCard.tsx, src/components/FormCard.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/props.ts, src/propsDefaults.ts
Note that `propDefaults` make non-optional interface attributes optional for the caller.
So `onSubmit: blabla` + `onSubmit: asyncNoop` === `onSubmit?: blabla`
=> Add standard propDefaults for form components

.storybook/config.tsx, .storybook/stories.css, src/components/EditableArrayCard.tsx, src/components/EditableCard.tsx, src/components/Form.tsx, src/components/FormCard.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/index.ts, src/props.ts, test/factories.ts, test/features/colProps.test.tsx, test/features/rowProps.test.tsx, test/utilities/FormManager.test.tsx
- Created standard `Form` component
- Changed components `FormCard`, `FormDrawer`, `FormModal` to use `Form`
- Form layout changed to vertical, removing label spacing and `:`
- Form controls aligned right
- Horizontal rule added over form controls
- Form controls aligned right
- Now properly implements `saveText`
- Form layout changed to vertical, removing label spacing and `:`
=> Standardize and simplify forms with Form component

src/inputs/ObjectSearchCreate.tsx, src/inputs/ObjectSearchCreateSearchInput.tsx, stories/types.stories.tsx, test/types/objectSearchCreate.test.tsx
- Add configurable help text when no search text entered
- Add configurable help text when no results returned
- Allow `placeholder` to be passed down to search
=> Add configurable help text to ObjectSearchCreate

src/inputs/ObjectSearchCreateSearchInput.tsx, stories/types.stories.tsx, test/types/objectSearchCreate.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/96
> ObjectSearchCreate does not update value in form state on clear #96
Closes https://github.com/mighty-justice/fields-ant/issues/95
> ObjectSearchCreate visually clears search on de-focus, but not in state #95
=> Fix ObjectSearchCreate search state bugs

src/building-blocks/ButtonToolbar.tsx, src/inputs/ObjectSearchCreate.tsx
https://thatsmighty.atlassian.net/browse/REG-196
Note: At the beginning I wanted that for any fields-ant fields, but I don't think it make much sense for things like <Input />s, <RadioButton />s.
The goal is for OSC to display extra data when an item is selected, which is more likely to happen with OSC vs anything else.
=> Allow OSC to render children

src/inputs/ObjectSearchCreateSearchInput.tsx
The`optionLabelProp` thing is fixing this issue :
=> OSC Props fix + fix custom rendered option item selection display

src/utilities/FormManager.ts, test/features/insertIf.test.tsx, test/features/readWriteOnly.test.tsx
- Added failing test
- Added failing test
=> Filter readOnly and insertIf values from model on submit

src/utilities/FormManager.ts, test/utilities/FormManager.test.tsx
This is to simplify the coming error-customization changes.
=> Pass full error and rename handleBackendResponse to handleRequestError

src/consts.ts, src/inputs/Birthdate.tsx, src/utilities/types.ts, stories/types.stories.tsx, test/factories.ts, test/types/birthdate.test.tsx, test/utilities/FormManager.test.tsx
My initial version of this included this function I loved but removed after a much better implementation:
```ts
private static isWAT (field: string, fieldValue: number) {
// This function is for dealing with a JS WAT
// https://www.destroyallsoftware.com/talks/wat
// Months start with zero in JS because of Java
// https://stackoverflow.com/a/41992352/224873
// Months start with zero in Java because of C
// Months start with zero in C because of array indexing
// Arrays start with zero because of pointer math
return field === 'months' && isNumber(fieldValue);
}
```
=> Add Birthdate type / component

src/building-blocks/NestedFieldSet.tsx, src/utilities/common.ts, test/types/objectSearchCreate.test.tsx
Allows for `rowProps` and `legend` to be passed into `FormFieldSet`.
Fixes https://github.com/mighty-justice/fields-ant/issues/159.
=> Allow complex nested field sets

src/utilities/common.ts
Also verified this earlier error addition works:
=> Better error messages around getOptions

src/inputs/ObjectSearch.tsx, src/inputs/ObjectSearchCreate.tsx, test/types/objectSearch.test.tsx, test/types/objectSearchCreate.test.tsx
**JIRA:** https://thatsmighty.atlassian.net/browse/MTY-962
Closes https://github.com/mighty-justice/fields-ant/issues/155
=> ObjectSearchCreate: searchFields or endpoint changing should clear results cache

src/building-blocks/FormField.tsx, src/building-blocks/FormFieldSet.tsx, src/building-blocks/NestedFieldSet.tsx, src/components/Form.tsx, src/inputs/ObjectSearch.tsx, src/inputs/ObjectSearchCreate.tsx, src/utilities/FormManager.ts, src/utilities/common.tsx, src/utilities/fillIn.ts
The changes made for https://thatsmighty.atlassian.net/browse/MTY-1035 totally destroyed the speed increases we made to support 150+ input forms. This PR brings performance back in line with before the change.
`formManager.formModel` is by far the most expensive operation when rendering. This change significantly reduces the number of times it has to be called, down to near 1 per render.
=> Add formModel prop to Form sub-components for significant speed increases

src/interfaces.ts
There are situations where we want to set `rowProps` but not show a legend.
=> Don't require a legend on fieldSets

src/components/Form.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/props.ts, src/propsDefaults.ts, test/components/FormDrawer.test.tsx, test/components/FormModal.test.tsx
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1094
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1095
- Create `ISharedFormModalProps` for both components to use
- Add `isVisible` SmartBool` to `FormModal`
- Make `isVisible` optional in both modals, default to always showing
- Automatically call isVisible.setFalse on `onSuccess` and `onCancel` if they are not specified
- Default side-modal width to 600px, to minimize the number of required props needed.
=> Standardize props / behavior between FormModal and FormDrawer

src/components/EditableArrayCard.tsx, src/components/EditableCard.tsx, src/components/Form.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/props.ts, src/propsDefaults.ts, src/utilities/common.tsx, test/components/EditableCard.test.tsx, test/features/blockSubmit.test.tsx
Since we use onSuccess to determine if `isVisible` should be changed or not, we shouldn't include it in the defaults.
=> Cover blockSubmit and other minor improvements

src/components/FormDrawer.tsx, src/components/FormModal.tsx, test/components/FormModal.test.tsx
These changes are required to make modals perform a bit closer to how they performed before 0.2, which is not rendering at all unless they are being shown.
Also changed FormDrawer so it inherits from FormModal and removes a ton of code.
=> Reduce code in FormDrawer and don't render hidden modals

src/building-blocks/NestedFieldSet.tsx, src/inputs/ObjectSearchCreate.tsx
Technical title: Wrap ObjectSearchCreate NestedFieldSet in Antd.Form.Item for spacing
This spacing issue was discovered while working on https://thatsmighty.atlassian.net/browse/MTY-886
=> Add spacing under create fields on ObjectSearchCreate

src/components/Form.tsx, test/components/FormCard.test.tsx
Even though the form modal won't submit, the save button should be disabled if there is a custom validation error. 
JIRA: https://thatsmighty.atlassian.net/secure/RapidBoard.jspa?rapidView=31&projectKey=MTY&modal=detail&selectedIssue=MTY-470
Current:
=> Disable submit button on form validation errors

src/utilities/FormManager.ts, test/utilities/FormManager.test.tsx
**JIRA**: https://thatsmighty.atlassian.net/secure/RapidBoard.jspa?rapidView=31&projectKey=MTY&modal=detail&selectedIssue=MTY-1149&assignee=karen
Github: https://github.com/mighty-justice/fields-ant/issues/189
Now: httpStatus.BAD_REQUEST is processed by FormManager and the useful messages presented to the user. 
These should also be presented to users, just like 400 errors.
The 'fix' . is probably just modifying the if statement to include both 400 and 403, but a test should be added for the use-case in the Github issue.
=> Add descriptive error messages for 403 forbidden

src/utilities/FormManager.ts, test/features/submitButtonDisabled.test.ts
JIRA: https://thatsmighty.atlassian.net/browse/MTY-1223
BEFORE:
AFTER:
=> Bugfix: Submit is disabled when editing forms with nested objects

src/inputs/ObjectSearch.tsx, test/types/objectSearch.test.ts, test/types/objectSearchCreate.test.ts
This change is actually for a side-project of mine that returns a 400 on empty searches. Right now that crashes ObjectSearch.
This will require very minor changes to places that use objectSearchCreate to re-add the / at the beginning and end.
=> Breaking change: ObjectSearchCreate takes full endpoint URL and handles errors

src/inputs/Date.tsx, test/types/date.test.ts
**JIRA**: https://thatsmighty.atlassian.net/browse/MTY-1313
Previously the date component was autofilling to 00-00 when deleting the month and date, which would raise form validation errors when the date was filled in and then deleted.
=> Fix date autofill

src/components/Card.tsx
Even if the documentation mentions it, specifying a `className` in the `<Card />` `props` doesn't apply it to the `<Card />`.
**PROOF OF DOCUMENTATION:**
**Testing the changes:**
=> Allow <Card> component to receive a custom className

src/inputs/ObjectSearch.tsx, stories/9_misc.stories.tsx, test/factories.ts, test/types/objectSearch.test.ts, test/types/objectSearchCreate.test.ts
- adds support for multiselect in ObjectSearch.
- also adds `onChange` to `IObjectSearchProps` to fix https://github.com/mighty-justice/fields-ant/issues/240
=> Support multiselect in ObjectSearch

src/inputs/ObjectSearch.tsx
Store previously selected options because options get cleared on each search.
=> Fix ObjectSearch multiselect

src/inputs/ObjectSearchCreate.tsx
Follow up to #241 .
To be passed as an edit prop, the param `isOptionDisabled` must be added to the OSC interface and specifically picked from `editProps`.
=> Fix to pass isOptionDisabled in ObjectSearchCreate edit props

src/inputs/TrimWhitespaceInput.tsx, src/utilities/types.ts, test/types/trimWhitespaceInput.test.ts
If you copy and paste an email/website in the email/website fields and there is a space, it won’t let you save the email/website. This PR trims the spaces on both fields since there should never be whitespace on either
Will share Ngrok link upon request
=> Add trim whitespace component and apply to url and email fields

dist/fieldsAnt.cjs.js, src/utilities/FormManager.ts, test/features/processErrors.test.ts, test/utilities/FormManager.test.tsx
Add toast notification duration so that backend validation errors disappear
=> Add toast notification duration

src/utilities/types.ts
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-2292
As seen in the bug above, datepicker should nullify like date.
=> Datepicker should nullify empty values

src/building-blocks/ButtonToolbar.tsx, src/building-blocks/FieldSet.tsx, src/building-blocks/FormItem.tsx, src/building-blocks/Info.tsx, src/inputs/Address.tsx, src/inputs/ObjectSearchCreate.tsx, src/interfaces.ts, src/props.ts
**Bug:**
**Problem:** `export type IClassName = ClassValue[];` should be `ClassValue`
**Solution:** Just use `ClassValue` throughout library.
=> Fix type of className

src/components/Table.tsx
=> Hide table pagination by default on single-page tables

.storybook/stories.css, src/building-blocks/CardField.tsx, src/building-blocks/CardFieldSet.tsx, src/building-blocks/Info.tsx, src/components/ArrayCard.tsx, src/components/Card.tsx, src/components/EditableArrayCard.tsx, src/components/Form.tsx, src/interfaces.ts, src/props.ts, src/propsDefaults.ts, src/utilities/common.tsx, stories/3_features.stories.tsx, test/features/labelDataDisplay.test.ts
Restructure fields-ant to support left-right label-data display
- Card objects can display label-data vertically or inline with the optional `display` prop [`"horizontal"`, `"vertical"`, or `"inline"`]
- Card objects can display a `:` postfixed to the label with the optional `colon` prop [`boolean`]
- Form objects can display label-data vertically or inline with the optional `display` prop [`"horizontal"`, `"vertical"`, or `"inline"`]
- Form objects can display a `:` postfixed to the label with the optional `colon` prop [`boolean`]
- Defaults for Card is `"vertical"` and Form label-data display is `"horizontal"` (this is currently how it is on our app)
- `"horizontal"` is equivalent to the default non-form Card objects
Card left/right:
Card vertical:
Form left/right:
Form vertical:
Colon …
=> Add left-right label-data support

.storybook/stories.css, src/building-blocks/CardFieldSet.tsx, src/building-blocks/FieldSet.tsx, src/building-blocks/FormField.tsx, src/building-blocks/FormFieldSet.tsx, src/building-blocks/FormItem.tsx, src/components/Form.tsx, stories/3_features.stories.tsx, test/features/labelDataDisplay.test.ts
Updated the `horizontal` and `inline` `layout` options to reflect that of ant design's [Form](https://ant.design/components/form/) `layout` options.
Patch for [MTY-3412](https://thatsmighty.atlassian.net/browse/MTY-3412)
All screenshots are of a form component with no row/col props and completely unformatted. Only differences are layout types
**Vertical [default]:**
**Horizontal:**
**Inline:**
=> Match layout features to ant-design's form

src/building-blocks/FormItem.tsx, src/building-blocks/Info.tsx, src/components/Form.tsx, src/consts.ts, src/utilities/common.tsx, test/features/labelDataDisplay.test.ts
Add `className` for colon on `formItem`. This is a requirement to add styles in registry.
Patch for [MTY-3412](https://thatsmighty.atlassian.net/browse/MTY-3412)
=> Add form class names for colon

src/building-blocks/Info.tsx
Fix props on `Info` and `Label` so these components can be independently used without needing a `format` prop.
Patch for [MTY-3412](https://thatsmighty.atlassian.net/browse/MTY-3412)
=> Fix info and label props

src/components/Card.tsx, src/components/FormCard.tsx, src/propsDefaults.ts
Allow boolean border property to be added to any `Card` type. Default is bordered.
=> Add card border property

dist/fieldsAnt.cjs.js
This PR adds the field `className` to read view of the form items.
=> Inlcude custom className for info row (read view) on form

src/utilities/FormManager.ts
Make argument for `formManager`'s `onFinish` function optional. This causes errors in the Registry where `onFinish` is called without any arguments
=> Make argument for formManager's onFinish optional

src/inputs/ObjectSearchCreate.tsx, test/types/objectSearch.test.ts, test/types/objectSearchCreate.test.ts
Add `id` prop to all implementations of `ObjectSearch` + add test case
=> Fix: objectSearchCreate input id

test/types/date.test.ts
This is an attempt to fix the `jest.setTimeout.Error` on the `date.test.ts`'s `validate` test when trying to deploy a new version
This is the first of two ideas to fix the issue:
1) Fix act errors
2) Add a default timeout for that particular test to give a greater buffer (maybe 10000ms)
**Note:** only the contents of [this pr](https://github.com/mighty-justice/fields-ant/pull/449) have been changed since the last version `v1.8.2`
=> Fix: Date validation test act errors

src/utilities/FormManager.ts
- The `disabled` prop should probably only affect the submit button
- I think the only time we'd really want to disable the cancel button is when the form is saving
**JIRA**: https://thatsmighty.atlassian.net/browse/PROD-1533
**QA**: https://mighty.testpad.com/script/168#49// (0039-0043)
=> Do not disable cancel button if disabled prop is true

src/components/EditableCard.tsx, test/components/EditableCard.test.ts
**JIRA**: https://thatsmighty.atlassian.net/browse/PROD-506
CoOp pull request: https://github.com/mighty-justice/coop-client/pull/1198
Tested in Storybook (ended up removing the Storybook code, thought it might be overkill):
Also tested in CoOp:
=> Add option to disable delete button if model has protected object
