mighty-justice/fields-ant

src/building-blocks/FormField.tsx, src/building-blocks/FormFields.tsx, src/components/FormCard.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/utilities/common.ts
This update brings `fields-ant` closer to V2 and adds legend support allowing me to implement it on Registry.
=> Break FormField out of FormFields, add legend

src/inputs/OptionSelect.tsx
This brings OptionSelect in line with changes made in the registry.
=> Add option sorting to OptionSelect

src/interfaces.ts
This is only an external interface issue.
=> Add objectSearchCreate interface to FieldConfig

src/inputs/ObjectSearchCreate.tsx, src/interfaces.ts
Closes https://github.com/mighty-justice/fields-ant/issues/16
Closes https://github.com/mighty-justice/fields-ant/issues/17
Closes https://github.com/mighty-justice/fields-ant/issues/19
=> Add search filters, create fields, back to ObjectSearchCreate

src/index.ts, src/inputs/OptionSelect.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/20
Also reworks index to include ALL components in export.
**Before:**
**After:**
=> Filter options in OptionSelect by label

src/building-blocks/FormFields.tsx, src/components/FormCard.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx
This allows the use of this component with any layout, being less prescriptive
=> Make FormFields component return a fragment, not a div

.travis.yml
=> Add lint step to TravisCI

.storybook/config.js, .storybook/stories.css, src/components/FormCard.tsx, src/index.ts, src/inputs/RadioGroup.tsx, src/utilities/FormManager.ts, src/utilities/types.ts, stories/index.stories.js
Closes https://github.com/mighty-justice/fields-ant/issues/36
=> Add option type and improve Storybook

src/building-blocks/FormFieldSet.tsx, src/components/FormCard.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/index.ts, src/inputs/ObjectSearchCreate.tsx
Makes more sense since it takes a fieldSet and renders fieldSet stuff.
=> Rename FieldFields to FormFieldSet

src/building-blocks/CardFieldSet.tsx, src/building-blocks/FormFieldSet.tsx, src/components/Card.tsx, test/features/insertIf.test.js
Closes https://github.com/mighty-justice/fields-ant/issues/38
=> Filter empty fieldSets in form and card

dist/inputs/ObjectSearchCreate.d.ts, src/inputs/ObjectSearchCreate.tsx
**note:** This might not be the best long term solution, but w/ Robert gone an given how complex that component is, I think this is the most simple and bug free solution for now.
We will revisit how we can properly allow customizing this component in the future.
=> Allow to customize OSC Select & Button

src/building-blocks/FormField.tsx, src/building-blocks/FormFieldSet.tsx, src/interfaces.ts, stories/types.stories.js
It's likely that we review it when Robert gets back, but it feels like that's a clean enough solution for now.
Note: I wouldn't  worry about the coverage since the code "might" change.
=> Add Rows and Columns logic in Forms

docs/Interfaces.md, docs/Utilities.md, src/building-blocks/CardFieldSet.tsx, src/components/ArrayCard.tsx, src/components/Card.tsx, src/components/EditableArrayCard.tsx, src/components/EditableCard.tsx, src/components/FormCard.tsx, src/components/FormModal.tsx, src/components/SummaryCard.tsx, src/interfaces.ts, test/components/ArrayCard.test.js, test/components/Card.test.js, test/components/EditableArrayCard.test.js, test/components/EditableCard.test.js, test/components/FormCard.test.js, test/components/FormModal.test.js, test/components/SummaryCard.test.js, test/features/insertIf.test.js, test/features/showLabel.test.js, test/types/date.test.js, test/types/objectSearchCreate.test.js, test/types/optionSelect.test.js, test/types/percentage.test.js, test/types/radio.test.js, test/utilities/FormManager.test.js
- Remove cardConfig prop wrapper
- Rename ICardConfig to ICommonCardProps
=> Remove cardConfig prop wrapper

src/components/FormDrawer.tsx
This brings `FormDrawer` in line with our other form components.
=> Add support for defaults to FormDrawer

src/components/FormCard.tsx, src/components/FormModal.tsx, src/components/SummaryCard.tsx, test/factories.js, test/features/isLoading.test.js
This brings `FormCard` in line with our other components:
=> Add isLoading prop to FormCard

src/building-blocks/CardField.tsx, src/building-blocks/CardFieldSet.tsx, src/building-blocks/FormField.tsx, src/building-blocks/FormFieldSet.tsx, src/building-blocks/NestedFieldSet.tsx, src/components/ArrayCard.tsx, src/components/Card.tsx, src/components/EditableCard.tsx, src/components/FormCard.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/components/SummaryCard.tsx, src/inputs/ObjectSearch.tsx, src/inputs/ObjectSearchCreate.tsx, src/inputs/OptionSelect.tsx, src/inputs/OptionSelectDisplay.tsx, src/inputs/Rate.tsx, src/interfaces.ts, src/props.ts, src/utilities/FormManager.ts, src/utilities/common.ts, test/components/FormCard.test.js
Also includes some generic standardization of imports across the library.
=> Replace many vague anys with named types

src/building-blocks/CardField.tsx, src/building-blocks/CardFieldSet.tsx, src/components/ArrayCard.tsx, src/components/Card.tsx, src/components/EditableArrayCard.tsx, src/components/EditableCard.tsx, src/components/FormCard.tsx, src/components/FormDrawer.tsx, src/components/FormModal.tsx, src/components/SummaryCard.tsx, src/interfaces.ts, src/props.ts
Does increasing inheritance in component interfaces improve the codebase?
=> Move some shared prop definitions into props file

.storybook/config.js, src/interfaces.ts, stories/_index.stories.js, stories/components.stories.js, stories/features.stories.js, test/factories.js, test/types/types.test.js
The main purpose if this PR is adding all the final types to `TYPE_GENERATORS` and all the final components to `COMPONENT_GENERATORS`. This allows all types and components to be included in some generic testing as well as added to the storybook documentation.
=> Add all Components / Types to automated tests / docs

src/building-blocks/FormField.tsx, src/building-blocks/FormFieldSet.tsx, src/building-blocks/NestedFieldSet.tsx, src/components/Form.tsx, src/inputs/ObjectSearchCreate.tsx, src/utilities/FormManager.ts, test/features/insertIf.test.tsx
Preliminary PR to fix https://github.com/mighty-justice/fields-ant/issues/67
=> Get form from FormManager; Remove all form props

src/building-blocks/FormField.tsx, src/building-blocks/FormFieldSet.tsx, src/building-blocks/NestedFieldSet.tsx, src/components/Form.tsx, src/props.ts, src/utilities/FormManager.ts
Part 2 of 3 on the road to https://github.com/mighty-justice/fields-ant/issues/67
=> Move defaults calculation into FormManager

src/consts.ts, src/inputs/ObjectSearchCreate.tsx, src/inputs/ObjectSearchCreateSearchInput.tsx, stories/types.stories.tsx
- Improve classnames on ObjectSearchCreate
- Fix `debounceWait` not included in props
- Small changes to shave lines off https://github.com/mighty-justice/fields-ant/pull/84/
=> Improve classNames on ObjectSearchCreate

src/building-blocks/FormField.tsx, src/building-blocks/FormFieldSet.tsx, src/utilities/FormManager.ts, test/features/insertIf.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/67
=> insertIf receives default values on initial form render

src/inputs/ObjectSearchCreate.tsx, src/inputs/ObjectSearchCreateSearchInput.tsx, stories/types.stories.tsx, test/types/objectSearchCreate.test.tsx
=> Move ObjectSearchCreate Add New to dropdown

src/inputs/ObjectSearchCreateSearchInput.tsx
=> Fix noSearch rendering issue

src/building-blocks/FormField.tsx, src/inputs/ObjectSearchCreate.tsx, src/inputs/ObjectSearchCreateSearchInput.tsx, src/inputs/RadioGroup.tsx, src/inputs/Rate.tsx, src/interfaces.ts, stories/types.stories.tsx
https://thatsmighty.atlassian.net/browse/REG-197
=> Enable IFieldConfigBase.className and apply it on <Antd.Form.Item>

src/inputs/ObjectSearchCreate.tsx, src/inputs/ObjectSearchCreateSearchInput.tsx, src/inputs/OptionSelect.tsx, src/interfaces.ts, stories/types.stories.tsx
https://thatsmighty.atlassian.net/browse/REG-198
=> Allow <Antd.Select.Option> custom rendering

package.json, src/consts.ts, src/inputs/OptionSelectDisplay.tsx, src/utilities/types.ts, test/factories.ts, test/features/insertIf.test.tsx, test/types/types.test.tsx, yarn.lock
=> Add types: url, ssn, phone, password, hidden

src/components/FormDrawer.tsx, src/props.ts
🤷‍♂️ 
(allow custom style fixes, currently impossible)
=> Enable className on <FormDrawer />

package.json, src/building-blocks/CardField.tsx, src/components/SummaryCard.tsx, src/index.ts, src/interfaces.ts, src/utilities/FormManager.ts, src/utilities/common.ts, src/utilities/types.ts, test/components/FormCard.test.tsx, test/utilities/FormManager.test.tsx, yarn.lock
```ts
renderValue (fieldConfigPartial: IFieldConfigPartial, model?: IModel): React.ReactNode
getFieldSetsFields (fieldSets: IFieldSet[]): IFieldConfig[]
```
=> Add renderValue and getFieldSetsFields utilities

src/utilities/FormManager.ts, src/utilities/common.ts, test/utilities/FormManager.test.tsx
Preliminary PR on the way to https://github.com/mighty-justice/fields-ant/issues/98
=> Move model processing into utility

src/components/Form.tsx, src/props.ts, stories/features.stories.tsx
=> Support full-width submit buttons on forms

src/interfaces.ts, src/utilities/FormManager.ts, src/utilities/common.ts, src/utilities/types.ts
Another PR on the road to https://github.com/mighty-justice/fields-ant/issues/98
=> Rework toForm and fromForm interfaces to closer match render

src/consts.ts, src/inputs/ObjectSearchCreate.tsx, src/utilities/FormManager.ts, src/utilities/common.ts, test/types/objectSearchCreate.test.tsx, test/utilities/FormManager.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/98
=> Nullify appropriate createFields in objectSearchCreate

docs/Interfaces.md, src/interfaces.ts
Closes https://github.com/mighty-justice/fields-ant/issues/124
=> Update interface documentation

src/building-blocks/FormField.tsx, src/interfaces.ts, stories/features.stories.tsx, stories/tslint.json, test/features/fieldsValidator.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/115
=> Implement much more sane and powerful validation option

src/inputs/OptionSelect.tsx, test/types/optionSelect.test.tsx
JIRA: https://thatsmighty.atlassian.net/browse/MTY-537
=> Show option search by default if scrollable

src/inputs/Birthdate.tsx, src/utilities/types.ts, test/types/birthdate.test.tsx
JIRA 1: https://thatsmighty.atlassian.net/browse/MTY-506
JIRA 2: https://thatsmighty.atlassian.net/browse/MTY-507
=> Future dates are invalid and infer 'YY dates in Birthdate

package.json, src/inputs/Birthdate.tsx, yarn.lock
Better at small sizes, as low at 480px:
=> Sizing and validation tweaks for Birthdate

src/inputs/Date.tsx, src/utilities/common.ts, src/utilities/types.ts, test/factories.ts, test/types/birthdate.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/149
=> Rename date to datepicker and birthdate to date

src/inputs/Date.tsx, src/utilities/common.ts
Closes https://github.com/mighty-justice/fields-ant/issues/147
=> Change date placeholders to MM DD YYYY

src/inputs/Date.tsx, test/types/date.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/148
**JIRA:** https://thatsmighty.atlassian.net/browse/MTY-961
=> Increment to next input box after 2 numbers in date input

src/inputs/ObjectSearchCreate.tsx, src/inputs/ObjectSearchCreateSearchInput.tsx, src/interfaces.ts, src/utilities/common.ts, src/utilities/types.ts, stories/types.stories.tsx, test/types/objectSearchCreate.test.tsx
**JIRA:** https://thatsmighty.atlassian.net/browse/MTY-963
Closes https://github.com/mighty-justice/fields-ant/issues/156
=> Improve renderOption, renderSelected attributes in ObjectSearchCreate

package.json, src/utilities/common.ts, src/utilities/getDateFormatList.ts, src/utilities/types.ts, test/utilities/getDateFormatList.test.ts
**JIRA:** https://thatsmighty.atlassian.net/browse/MTY-885
=> Expand the number of accepted input formats in datepicker

src/inputs/ObjectSearch.tsx, src/inputs/ObjectSearchCreate.tsx, src/utilities/types.ts, stories/types.stories.tsx, test/factories.ts
**JIRA:** https://thatsmighty.atlassian.net/browse/MTY-987
=> Add objectSearch type

src/building-blocks/FormFieldSet.tsx, src/building-blocks/NestedFieldSet.tsx, src/inputs/ObjectSearchCreate.tsx, test/types/objectSearchCreate.test.tsx
**JIRA:** https://thatsmighty.atlassian.net/browse/MTY-1006
Closes https://github.com/mighty-justice/fields-ant/issues/172
=> Bugfix: When clicking create in OSC, value is not being changed

src/inputs/ObjectSearch.tsx, test/types/objectSearch.test.tsx
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1009
Closes https://github.com/mighty-justice/fields-ant/issues/177
=> Bugfix: Clearing object search create input does not clear render on first click

src/utilities/common.tsx, test/features/tooltip.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/180
=> Bugfix: Tooltip not showing fieldConfig label

src/building-blocks/CardFieldSet.tsx, src/building-blocks/FormFieldSet.tsx, src/components/Card.tsx, src/components/Form.tsx, src/utilities/common.tsx, src/utilities/filters.ts, test/features/readWriteOnly.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/171
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1035
Note: This will significantly slow down fields-ant and will require a follow-up optimization PR.
=> Add filterFieldSet and filterFieldSets utilities

src/building-blocks/ButtonToolbar.tsx, src/building-blocks/CardField.tsx, src/building-blocks/CardFieldSet.tsx, src/building-blocks/GuardedButton.tsx, src/building-blocks/Info.tsx, src/building-blocks/Legend.tsx, src/building-blocks/WithTooltip.tsx, src/inputs/OptionSelect.tsx, src/inputs/Rate.tsx
Verified via yalc that this fixes the rendering issues on Registry.
=> Add observer and autobind to ALL components

src/components/EditableCard.tsx, test/components/EditableCard.test.tsx
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1096
=> Add ModalComponent prop to EditableCard

README.md, src/building-blocks/FormField.tsx, src/building-blocks/FormItem.tsx, src/index.ts, src/inputs/ObjectSearchCreate.tsx, test/types/types.test.tsx
Closes https://github.com/mighty-justice/fields-ant/issues/167
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-909
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1122
=> Bugfix: ObjectSearchCreate missing required asterisk and double bottom margins

src/components/Form.tsx, src/components/FormModal.tsx, src/utilities/FormManager.ts, test/components/FormCard.test.tsx, test/features/submitButtonDisabled.test.ts, test/features/submitButtonDisabled.test.tsx
JIRA: https://thatsmighty.atlassian.net/secure/RapidBoard.jspa?rapidView=31&projectKey=MTY&modal=detail&selectedIssue=MTY-1160
=> Disable submit button when FormModal has errors on the page

src/inputs/Checkbox.tsx, src/interfaces.ts, src/utilities/types.ts, test/factories.ts
=> Add checkbox component

src/inputs/ObjectSearch.tsx
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1310
=> Change add new text to more closely match usage

src/utilities/types.ts
**JIRA**: https://thatsmighty.atlassian.net/browse/MTY-1500
=> Remove website validation

package.json, src/global.d.ts, src/inputs/Address.tsx, src/interfaces.ts, test/types/address.test.ts, yarn.lock
Add ability to infer state from zipcode if `smart` is set to true
=> Infer state in address type

src/utilities/types.ts
**Jira:** https://thatsmighty.atlassian.net/browse/MTY-1500
=> Remove browser-validation for URLs from URl type

src/components/FormModal.tsx
https://thatsmighty.atlassian.net/browse/MTY-1591
=> Implement className prop in FormModal

src/inputs/ObjectSearch.tsx, src/interfaces.ts
See https://ant.design/components/select/#Option-props
=> Add support for disabled param to ObjectSearchCreate options

src/inputs/ObjectSearch.tsx, test/types/objectSearchCreate.test.ts
https://thatsmighty.atlassian.net/browse/MTY-1592
=> Change object search create UX to be more user-friendly

package.json, src/inputs/ObjectSearch.tsx
https://thatsmighty.atlassian.net/browse/MTY-1592
=> MTY-1592 Fix object search create to more intuitive based on CeCe's designs

src/inputs/ObjectSearch.tsx, src/inputs/ObjectSearchCreate.tsx, test/types/objectSearch.test.ts
=> Add searchOnEmpty prop to ObjectSearch and OSC

src/inputs/Checkbox.tsx, test/types/checkbox.test.ts
Test failing if you remove Checkbox.tsx changes:
=> Fix Checkbox not showing as reset after submit

src/building-blocks/FormField.tsx, src/inputs/Address.tsx, src/inputs/Date.tsx, src/inputs/ObjectSearch.tsx, test/types/types.test.ts
Added support for the disabled attribute for all types
=> Fix disable attribute of fieldConfig

src/building-blocks/FormField.tsx, src/building-blocks/FormItem.tsx, src/components/Form.tsx, src/components/FormModal.tsx, src/components/Table.tsx, src/inputs/ObjectSearch.tsx, src/inputs/ObjectSearchCreate.tsx, src/interfaces.ts, src/props.ts, src/utilities/FormManager.ts, src/utilities/common.tsx, stories/1_types.stories.tsx, stories/3_features.stories.tsx, test/features/submitButtonDisabled.test.ts, test/types/types.test.ts, test/utilities/FormManager.test.tsx
=> Add isCancelButtonDisabled; disabled docs page; improve types, tests

src/building-blocks/FormField.tsx, src/components/Form.tsx, src/props.ts, src/utilities/FormManager.ts, stories/1_types.stories.tsx, test/features/submitButtonDisabled.test.ts
=> Add disabled prop to form; disable while submitting

src/building-blocks/CardFieldSet.tsx, src/building-blocks/FieldSet.tsx, src/building-blocks/FormFieldSet.tsx, src/components/Card.tsx, src/components/FormModal.tsx, src/components/SummaryCard.tsx, src/components/Table.tsx, src/props.ts, stories/3_features.stories.tsx
=> Add FieldSet component to unify read/write display

.storybook/stories.css, src/building-blocks/CardField.tsx, src/building-blocks/Info.tsx, src/components/FormModal.tsx, src/index.ts, test/components/EditableCard.test.ts, test/utilities/getFieldSuffix.test.tsx
**Jira:** https://thatsmighty.atlassian.net/browse/TB-112
**Before**
**After**
=> Add layout support to Cards

src/building-blocks/Legend.tsx, src/consts.ts, test/features/colProps.test.ts
=> Move legend into a full-width row

src/utilities/backendValidation.ts, test/features/processErrors.test.ts, test/utilities/FormManager.test.tsx, test/utilities/backendValidation.test.tsx
Format backend validation response with array type, in addition to objects
=> Format backend validation response with array type

src/components/FormDrawer.tsx, src/utilities/FormManager.ts, test/components/FormCard.test.ts, test/features/blockSubmit.test.ts, test/features/formItemExtra.test.tsx, test/features/respondToFieldsetsChange.test.ts, test/features/successText.test.ts, test/features/value.test.ts, test/types/checkbox.test.ts, test/types/date.test.ts, test/types/optionSelect.test.ts, test/types/trimWhitespaceInput.test.ts, test/types/types.test.ts, test/utilities/FormManager.test.tsx
This bug was discovered during Emi's work on the dynamic cases form. A test existed for this use-case, but the test was insufficient. This PR improves the test suite and fixes the bug.
=> Fix: FieldSet changes shown on page but not included in submit model

src/components/FormCard.tsx, test/factories.ts, test/features/classNames.test.ts, test/features/labelDataDisplay.test.ts
Make sure `FormCard` uses the `className` prop
=> Fix: FormCard class names

src/inputs/ObjectSelect.tsx, src/inputs/RadioGroup.tsx, src/interfaces.ts
Add `disabled` to `IOption` used in `RadioGroup` and `ObjectSelect`
=> Add disabled to IOption

src/utilities/FormManager.ts
Mainly for this registry PR: https://github.com/mighty-justice/registry-client/pull/2695
=> Make event optional for onSave in FormManager

package.json, src/building-blocks/FormItem.tsx, src/building-blocks/WithTooltip.tsx, src/components/EditableArrayCard.tsx, src/components/EditableCard.tsx, src/components/Form.tsx, src/components/Table.tsx, src/inputs/Hidden.tsx, src/inputs/ObjectSearch.tsx, src/inputs/ObjectSearchCreate.tsx, src/interfaces.ts, src/utilities/FormManager.ts, stories/FieldConfigPreview.tsx, test/features/formItemExtra.test.tsx, test/features/labelDataDisplay.test.ts, test/features/tooltip.test.ts, test/setup.ts, test/types/objectSearch.test.ts, test/types/objectSearchCreate.test.ts, test/types/types.test.ts, yarn.lock
Upgrade Ant Design to version 4 (with legacy Form)
=> Upgrade to Ant Design v4 (with legacy Form)

package.json, src/building-blocks/FormItem.tsx, src/building-blocks/NestedFieldSet.tsx, src/components/Form.tsx, src/components/FormModal.tsx, src/inputs/ObjectSearchCreate.tsx, src/interfaces.ts, src/utilities/FormManager.ts, src/utilities/common.tsx, src/utilities/fillIn.ts, src/utilities/types.ts, stories/3_features.stories.tsx, test/components/FormModal.test.ts, test/features/formItemExtra.test.tsx, test/features/insertIf.test.ts, test/features/labelDataDisplay.test.ts, test/features/processErrors.test.ts, test/features/submitButtonDisabled.test.ts, test/features/successText.test.ts, test/types/objectSearch.test.ts, test/types/objectSearchCreate.test.ts, test/types/types.test.ts, yarn.lock
**Jira:** https://thatsmighty.atlassian.net/browse/PROD-271
=> Ant Design 4 Form

.github/workflows/main.yml, src/building-blocks/FormField.tsx, src/utilities/FormManager.ts, src/utilities/filters.ts, test/features/insertIf.test.ts, test/features/resetOnSuccess.test.ts, test/types/checkbox.test.ts
**Jira:** https://thatsmighty.atlassian.net/browse/PROD-440
=> Switch to Github Actions and fix insertIf bug

src/utilities/FormManager.ts, src/utilities/common.tsx, src/utilities/flatten.ts, test/features/id.test.ts, test/features/nestedFormItems.test.ts, test/utilities/objectArrayNotation.test.ts
Fix handling of nested for item values
=> Fix: Nested form item values

test/types/date.test.ts
Follow up to https://github.com/mighty-justice/fields-ant/pull/450
=> Fix: flaky date test

.storybook/config.tsx, src/utilities/common.tsx, test/components/Table.test.tsx
**Jira:** https://thatsmighty.atlassian.net/browse/PROD-633
=> Fix deep rendering of table cells

package.json, src/utilities/fillIn.ts, test/types/objectSearchCreate.test.ts, test/utilities/fillIn.test.ts, yarn.lock
**Jira:** https://thatsmighty.atlassian.net/browse/PROD-664
Examples:
-  `Required - Please input a valid value` => `This field is required`
- `Required - Please input a valid Law Firm` => `'Law Firm' is required`
- `Required - Please input a valid Enter an external system identifier` => `'Enter an external system identifier' is required`
=> Improve required error message
